# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'grape'
gem 'thin'
gem 'http'
gem 'oj'
gem "mongoid"
gem "bson_ext", :platforms => :mri
